title = "Kwatafana"
output = "index.html"
primary_color = "#222D31"
secondary_color = "black"
tertiary_color = "cyan"


[sections]

[sections.navbar]
variant = "basic"
links = [{url= "https://github.com/kwatafana", text= "git"}, {url= "https://twitter.com/kwatafana", text= "twitter"}, {url= "./kaindume/index.html", text= "kaindume"}]

[sections.hero]
variant = "basic"
heading = "kwatafana.org"
sub_heading = "High grade software and networks.<br><small><em>email: kaindume (at) kwatafana (dot) org</em></small>"